= Upgrade to 3.10.11

== Breaking Changes

=== Platform policies execution order
The goal of policies at the platform level is to define them once and execute them for any APIs instead of having to duplicate the same configuration for each of the APIs.

Regarding the execution order of the policies, the behavior before 3.10.11 was:

- Platform request policies were executed before API request policies
- Platform response policies were executed before API response policies

To ensure the platform policies are always the first and last policies to be applied, and thus enforcing some behavior at the platform level, the execution order has been changed.

As of `3.10.11` the following rules apply:

- Platform request policies are executed *before* API request policies
- Platform response policies are executed *after* API response policies


== Liquibase execution
If you use a JDBC repository, we recommend disabling the liquibase scripts execution by the gateway. It will avoid some conflicts when upgrading and starting Gateway and Management API at the same time.
You can do that by adding this field in the `gravitee.yml` file:
[source,YAML]
----
 management:
   type: jdbc
   jdbc:
     liquibase: false
----