= Upgrade to 3.0.0

=== Environment
In this new version Gravitee comes with a new way of managing your environments.
By default, Gravitee is configured with a first Environment:
```json
environment {
	id: DEFAULT,
	name: Default environment
}
```

It will allow you to manage more than one environment for each instance of Gravitee.

If you are using the REST API directly, please note that you will have to adapt the URL
from `https://host/management/` to `https://host/management/DEFAULT/`

== Breaking Changes
=== API-Key policy
In this new version, if api-keys used to call an API is invalid or has expired, the gateway will fail with a *401* (instead of 403 in previous versions of Gravitee).

== Repository
=== Mongodb

Before running any script, please create a dump of your existing database.

upgrades/3.0.0/mongodb/1-collections-linked-to-environment.js::
This script adds a new field that refers the default environment.

upgrades/3.0.0/mongodb/2-id-migration.js::
This script changes the format of some collections id and drop some field.

upgrades/3.0.0/mongodb/3-replace-apiArray-by-unique-api.js::
This script adds a new field that refers the api and remove the api array.

