= Upgrade to 3.12.0

== Breaking Change

Policy plugin gravitee-policy-apikey prior to version 2.3.0 is no more compatible with APIM 3.12.0.

From this version, you have to use gravitee-policy-apikey >= 2.3.0.

== Default Settings Change Announcement

HTTP Bridge Service will be disabled by default starting in version 3.13.

If you are using this feature, **do not forget to update your settings.**

For more information, link:https://docs.gravitee.io/apim/3.x/apim_installguide_hybrid_deployment.html[click here] for documentation.

== Model

=== Api Keys

Before this version, APIKeys contained a *key* attribute, which is both the value of the key and also the database ID.

Starting in version 3.12.0, APIKeys now contain distinct attributes:

- *key* : api key value
- *id* : api key database unique id

The 3 Portal API endpoints listed below now expose distinct *id* and *key* in the HTTP response (previously, the key attribute was exposed as '*id*') :

- GET /subscriptions/{subscriptionId}
- POST /subscriptions/{subscriptionId}
- POST /subscriptions/{subscriptionId}/_renew

== Repository

=== MongoDB

Before running any script, please create a dump of your existing database.

https://raw.githubusercontent.com/gravitee-io/release/master/upgrades/3.x/3.12.0/mongodb/api-keys-migration.js[upgrades/3.x/3.12.0/mongodb/api-keys-migration.js]::
This script adds *key* and *api* columns in api keys *keys* table.
