= Upgrade to 3.0.0
== General
=== Organization & Environment
In this new version Gravitee comes with a new way of managing your environments.
By default, Gravitee is configured with a first Organization:
```json
organization {
	id: DEFAULT,
	name: Default organization
}
```
And a first Environment in this Organization:
```json
environment {
	id: DEFAULT,
	name: Default environment,
	organization: DEFAULT
}
```

It will allow you to manage more than one environment for each instance of Gravitee.

== Breaking Changes
=== API-Key policy
In this new version, if api-keys used to call an API is invalid or has expired, the gateway will fail with a *401* (instead of 403 in previous versions of Gravitee).

=== Management API
If you are using the REST API directly, please note that you will have to adapt the URL
from `https://host/management/` to `https://host/management/DEFAULT/`

=== Management UI
The actual portal has been replaced by a brand new version, with its own location. As a consequence, the URL of the management UI has been modified to remove the */management* part.

For instance, to access the _Platform Overview_ page, you should use `https://host/\#!/platform` instead of `https://host/#!/management/platform`

== Repository
=== Mongodb

Before running any script, please create a dump of your existing database.

https://raw.githubusercontent.com/gravitee-io/release/master/upgrades/3.0.0/mongodb/1-collections-linked-to-environment.js[upgrades/3.0.0/mongodb/1-collections-linked-to-environment.js]::
This script adds new fields that refer the default environment or the default organization.

https://raw.githubusercontent.com/gravitee-io/release/master/upgrades/3.0.0/mongodb/2-roles-groups-and-memberships-migration.js[upgrades/3.0.0/mongodb/2-roles-groups-and-memberships-migration.js]::
This script migrates permission values in roles since MANAGEMENT roles and PORTAL roles have been merged and dispatched into new ENVIRONMENT and ORGANIZATION roles.
It also updates memberships and groups by adding or removing columns.


https://raw.githubusercontent.com/gravitee-io/release/master/upgrades/3.0.0/mongodb/3-replace-apiArray-by-unique-api.js[upgrades/3.0.0/mongodb/upgrades/3.0.0/mongodb/3-replace-apiArray-by-unique-api.js]::
This script adds a new field that refers the api and remove the api array.

== Upgrader
=== Identity providers
Because of the evolution of the roles and their scope, role mappings in *Identity Providers* must be updated. To achieve this, a specific service has been created and will be launched at APIM startup. As this is not necessary to launch this service more than once, it can be disabled with some configuration.
[source, yaml]
----
services:
  # v3 upgrader service. Can be disabled after first launch.
  v3-upgrader:
    enabled: true
----
