= Upgrade to 3.0.0

=== Organization & Environment
In this new version Gravitee comes with a new way of managing your environments.
By default, Gravitee is configured with a first Organization:
```json
organization {
	id: DEFAULT,
	name: Default organization
}
```
And a first Environment in this Organization:
```json
environment {
	id: DEFAULT,
	name: Default environment,
	organization: DEFAULT
}
```

It will allow you to manage more than one environment for each instance of Gravitee.

== Breaking Changes
=== API-Key policy
In this new version, if api-keys used to call an API is invalid or has expired, the gateway will fail with a *401* (instead of 403 in previous versions of Gravitee).

=== Management API
If you are using the REST API directly, please note that you will have to adapt the URL
from `https://host/management/` to `https://host/management/DEFAULT/`

=== Management UI
The actual portal has been replaced by a brand new version, with its own location. As a consequence, the URL of the management UI has been modified to remove the */management* part.

For instance, to access the _Platform Overview_ page, you should use `https://host/\#!/platform` instead of `https://host/#!/management/platform`

== Repository
=== Mongodb

Before running any script, please create a dump of your existing database.

https://raw.githubusercontent.com/gravitee-io/release/master/upgrades/3.0.0/mongodb/1-collections-linked-to-environment.js[upgrades/3.0.0/mongodb/1-collections-linked-to-environment.js]::
This script adds a new field that refers the default environment.

https://raw.githubusercontent.com/gravitee-io/release/master/upgrades/3.0.0/mongodb/2-id-migration.js[upgrades/3.0.0/mongodb/2-id-migration.js]::
This script changes the format of some collections id and drop some field.

https://raw.githubusercontent.com/gravitee-io/release/master/upgrades/3.0.0/mongodb/3-replace-apiArray-by-unique-api.js[upgrades/3.0.0/mongodb/upgrades/3.0.0/mongodb/3-replace-apiArray-by-unique-api.js]::
This script adds a new field that refers the api and remove the api array.

