= Upgrade to 3.9.0

== Memory management

Starting from this new version, the default Xms and Xmx parameters has been fixed to 256m.
Previous value was too high and does not reflect real memory usage for both the API Gateway and Management API.

If, for some reasons, you need to increase those default values, you can set the `GIO_MIN_MEM` and `GIO_MAX_MEM` environment variables in your scripts.
Those variables are then "injected" into the JAVA_OPTS during bootstrap.

== APIM API - Tags and Tenants

This version changes permissions' scope from `ENVIRONMENT` to `ORGANIZATION` for:
    * TAG
    * TENANT
    * ENTRYPOINT

These permissions are now readonly for the scope `ENVIRONMENT`. They will be deleted on version 3.10.
If you are using these permissions, please update them for the scope `ORGANIZATION`.

== Repository

=== Mongodb

Before running any script, please create a dump of your existing database.

https://raw.githubusercontent.com/gravitee-io/release/master/upgrades/3.x/3.9.0/mongodb/1-tags-and-tenants-migration.js[upgrades/3.x/3.9.0/mongodb/1-tags-and-tenants-migration.js]::
This script adds referenceId set to 'DEFAULT' and referenceType set to 'ORGANIZATION' to tags, tenants and entrypoint collections.

https://raw.githubusercontent.com/gravitee-io/release/master/upgrades/3.x/3.9.0/mongodb/2-events-migration.js[upgrades/3.x/3.9.0/mongodb/2-events-migration.js]::
This script modifies events, so an event can be linked to more than one environment.
